version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: app-postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my-app
    restart: always
    depends_on:
      - postgres
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_ADDITIONAL_PARAMS: ${DB_ADDITIONAL_PARAMS}
      REVISION: ${REVISION}
      BUILDTIME: ${BUILDTIME}
    ports:
      - "3000:3000"

volumes:
  postgres_data:
