// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package contact

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/melkishengue/gotemplate/pkg/utils"

func getMessagesBackendUrl() string {
	return utils.GetEnvOrDie("BACKEND_API_URL") + "/api/v1/internal/messages"
}

func Contact() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full max-w-lg mx-auto my-10 bg-white/95 backdrop-blur-sm rounded-2xl shadow-2xl p-8 space-y-6\"><form id=\"form\" hx-target=\"this\" hx-post=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(getMessagesBackendUrl())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/contact/contact.templ`, Line: 14, Col: 36}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hx-swap=\"outerHTML\"><div class=\"text-center mb-8\"><h2 class=\"text-3xl font-bold text-gray-800 mb-2\">Get in Touch</h2><p class=\"text-gray-600\">We'd love to hear from you</p></div><div class=\"space-y-2\"><label for=\"email\" class=\"block text-sm font-semibold text-gray-700\">Email Address</label> <input type=\"email\" id=\"email\" name=\"email\" required placeholder=\"you@example.com\" class=\"w-full px-4 py-3 bg-gray-50 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-indigo-500 focus:bg-white transition-all duration-200\"></div><div class=\"space-y-2\"><label for=\"message\" class=\"block text-sm font-semibold text-gray-700\">Message</label> <textarea id=\"message\" name=\"message\" required rows=\"5\" placeholder=\"Tell us what&#39;s on your mind...\" class=\"w-full px-4 py-3 bg-gray-50 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-indigo-500 focus:bg-white transition-all duration-200 resize-none\"></textarea></div><button type=\"submit\" class=\"btn-app\" id=\"submit\">Send Message</button><div id=\"response\" class=\"\" font-bold></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
